#ifndef TOKENS_H
#define TOKENS_H

typedef enum {

    TOKEN_INTEIRO,
    TOKEN_DECIMAL,
    TOKEN_TEXTO,
    TOKEN_LOGICO,

    TOKEN_VERDADEIRO,
    TOKEN_FALSO,

    TOKEN_LEIA,
    TOKEN_ESCREVA,
    TOKEN_SE,
    TOKEN_SENAO,
    TOKEN_ENQUANTO,
    TOKEN_PARA,

    TOKEN_ID,
    TOKEN_NUM_INT,
    TOKEN_NUM_DEC,
    TOKEN_STRING,

    TOKEN_MAIS,
    TOKEN_MENOS,
    TOKEN_MULT,
    TOKEN_DIV,
    TOKEN_POT,

    TOKEN_IGUAL,
    TOKEN_IGUAL_IGUAL,
    TOKEN_DIFERENTE,

    TOKEN_MAIOR,
    TOKEN_MENOR,
    TOKEN_MAIOR_IGUAL,
    TOKEN_MENOR_IGUAL,

    TOKEN_E,
    TOKEN_OU,

    TOKEN_PONTO_VIRGULA,
    TOKEN_VIRGULA,

    TOKEN_ABRE_PAR,
    TOKEN_FECHA_PAR,

    TOKEN_ABRE_CHAVE,
    TOKEN_FECHA_CHAVE,

    TOKEN_EOF,
    TOKEN_ERRO

} TokenType;

#endif
